version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      MONGODB_URI: ${MONGODB_URI}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      RABBITMQ_URL: ${RABBITMQ_URL}
      EXCHANGE_NAME: ${EXCHANGE_NAME}
      GROQ_API_KEY: ${GROQ_API_KEY}
